---
- name: Deploy Web Application on Nginx with Certbot
  hosts: wb01
  become: true

  vars:
    domain_name: netmoven.com
    email_address: karimanziramoven@gmail.com

  tasks:
    - name: Install EPEL repository (required for Certbot)
      yum:
        name: epel-release
        state: present

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Install Certbot and dependencies
      yum:
        name: certbot python3-certbot-nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create directory for web application
      file:
        path: /usr/share/nginx/html
        state: directory
        mode: 0755

    - name: Copy index.html to web application directory
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html

    - name: Set up Nginx configuration
      template:
        src: nginx_config.j2
        dest: /etc/nginx/sites-available/{{ domain_name }}
        mode: 0644
      notify:
        - Reload Nginx

    - name: Enable Nginx virtual host
      file:
        src: /etc/nginx/sites-available/{{ domain_name }}
        dest: /etc/nginx/sites-enabled/
        state: link

    - name: Obtain SSL certificates with Certbot
      shell: certbot --nginx --agree-tos --redirect --non-interactive --email {{ email_address }} -d {{ domain_name }}
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
